# Generated by Django 5.2.13 on 2026-04-25 00:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamigliaVino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('is_spumante', models.BooleanField(default=False, help_text='Se True, richiede cestello')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Famiglie vino',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='MovimentoMagazzino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CARICO', 'Carico'), ('SCARICO', 'Scarico (imbottigliamento)'), ('AGGIUNTA_VINO', 'Aggiunta vino al silos')], max_length=20)),
                ('categoria', models.CharField(choices=[('TAPPO', 'Tappo'), ('CARTONE', 'Cartone'), ('BOTTIGLIA', 'Bottiglia'), ('ETICHETTA', 'Etichetta'), ('CAPSULA', 'Capsula'), ('CESTELLO', 'Cestello'), ('VINO', 'Vino (litri)')], max_length=20)),
                ('quantita', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descrizione', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('riferimento_id', models.PositiveIntegerField(blank=True, null=True)),
                ('riferimento_tipo', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Movimenti magazzino',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='TipoBottiglia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('capacita_litri', models.DecimalField(decimal_places=2, help_text='Capacità in litri', max_digits=5)),
                ('quantita', models.PositiveIntegerField(default=0, help_text='Scorta in magazzino')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tipi bottiglia',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoCapsula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('quantita', models.PositiveIntegerField(default=0, help_text='Scorta in magazzino')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tipi capsula',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoCartone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('capacita_bottiglie', models.PositiveIntegerField(help_text='Quante bottiglie contiene (es: 6 per vino, 1 per spumante)')),
                ('quantita', models.PositiveIntegerField(default=0, help_text='Scorta in magazzino')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tipi cartone',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoCestello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('quantita', models.PositiveIntegerField(default=0, help_text='Scorta in magazzino')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tipi cestello',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoEtichetta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('quantita', models.PositiveIntegerField(default=0, help_text='Scorta in magazzino')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tipi etichetta',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoTappo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('quantita', models.PositiveIntegerField(default=0, help_text='Scorta in magazzino')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tipi tappo',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipologiaVino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantita_litri', models.DecimalField(decimal_places=2, default=0, help_text='Litri disponibili nel silos', max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('famiglia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipologie', to='winery.famigliavino')),
                ('tipo_bottiglia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='winery.tipobottiglia')),
                ('tipo_capsula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='winery.tipocapsula')),
                ('tipo_cartone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='winery.tipocartone')),
                ('tipo_cestello', models.ForeignKey(blank=True, help_text='Solo per spumante', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='winery.tipocestello')),
                ('tipo_etichetta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='winery.tipoetichetta')),
                ('tipo_tappo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='winery.tipotappo')),
            ],
            options={
                'verbose_name_plural': 'Tipologie vino',
                'ordering': ['famiglia__nome', 'nome'],
                'unique_together': {('nome', 'famiglia')},
            },
        ),
        migrations.CreateModel(
            name='LottoBottiglie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('stato', models.CharField(choices=[('SENZA_ETICHETTA', 'Senza etichetta'), ('COMPLETA', 'Completa')], default='SENZA_ETICHETTA', max_length=20)),
                ('ha_etichetta', models.BooleanField(default=False)),
                ('ha_capsula', models.BooleanField(default=False)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, default='')),
                ('tipologia_vino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotti', to='winery.tipologiavino')),
            ],
            options={
                'verbose_name_plural': 'Lotti bottiglie',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
