# Generated by Django 5.2.13 on 2026-05-02 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentomagazzino',
            name='tipo',
            field=models.CharField(choices=[('CARICO', 'Carico'), ('SCARICO', 'Scarico (imbottigliamento)'), ('AGGIUNTA_VINO', 'Aggiunta vino al silos'), ('ANNULLAMENTO', 'Annullamento operazione')], max_length=20),
        ),
        migrations.CreateModel(
            name='OperazioneImbottigliamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREA_SENZA_ETICHETTA', 'Crea senza etichetta'), ('CREA_CON_ETICHETTA', 'Crea con etichetta'), ('ASSOCIA_ETICHETTA', 'Associa etichetta')], max_length=30)),
                ('stato', models.CharField(choices=[('ATTIVA', 'Attiva'), ('ANNULLATA', 'Annullata')], default='ATTIVA', max_length=20)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('data_annullamento', models.DateTimeField(blank=True, null=True)),
                ('quantita', models.PositiveIntegerField()),
                ('con_etichetta', models.BooleanField(default=False)),
                ('con_capsula', models.BooleanField(default=False)),
                ('dettagli', models.JSONField(default=dict)),
                ('note', models.TextField(blank=True, default='')),
                ('tipologia_vino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operazioni', to='winery.tipologiavino')),
                ('tipologia_vino_destinazione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operazioni_dest', to='winery.tipologiavino')),
            ],
            options={
                'verbose_name_plural': 'Operazioni imbottigliamento',
                'ordering': ['-data'],
            },
        ),
    ]
