# Generated by Django 5.2.15 on 2026-06-10 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0002_alter_movimentomagazzino_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('quantita', models.PositiveIntegerField(default=0, help_text='Scorta in magazzino')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Tipi gadget',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterField(
            model_name='movimentomagazzino',
            name='categoria',
            field=models.CharField(choices=[('TAPPO', 'Tappo'), ('CARTONE', 'Cartone'), ('BOTTIGLIA', 'Bottiglia'), ('ETICHETTA', 'Etichetta'), ('CAPSULA', 'Capsula'), ('CESTELLO', 'Cestello'), ('GADGET', 'Gadget'), ('VINO', 'Vino (litri)')], max_length=20),
        ),
    ]
