# Generated by Django 5.2.15 on 2026-06-13 13:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winery', '0003_tipogadget_alter_movimentomagazzino_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cognome', models.CharField(max_length=120)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Agenti',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome referente / privato', max_length=200)),
                ('azienda', models.CharField(blank=True, default='', max_length=200)),
                ('via', models.CharField(blank=True, default='', help_text='Indirizzo completo', max_length=300)),
                ('partita_iva', models.CharField(blank=True, default='', max_length=30)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Clienti',
                'ordering': ['azienda', 'nome'],
            },
        ),
        migrations.AlterField(
            model_name='movimentomagazzino',
            name='tipo',
            field=models.CharField(choices=[('CARICO', 'Carico'), ('SCARICO', 'Scarico (imbottigliamento)'), ('AGGIUNTA_VINO', 'Aggiunta vino al silos'), ('ANNULLAMENTO', 'Annullamento operazione'), ('ORDINE_SCARICO', 'Scarico per ordine'), ('ORDINE_RIPRISTINO', 'Ripristino per annullamento ordine')], max_length=20),
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(editable=False, unique=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('sconto_percentuale', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Sconto applicato sul totale (es: 10 = 10%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('aliquota_iva', models.DecimalField(decimal_places=2, default=Decimal('22'), help_text='Aliquota IVA in percentuale (es: 22 = 22%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('tracking_number', models.CharField(blank=True, default='', max_length=100)),
                ('pacco_arrivato', models.BooleanField(default=False)),
                ('fattura_pagata', models.BooleanField(default=False)),
                ('stato', models.CharField(choices=[('CONFERMATO', 'Confermato'), ('ANNULLATO', 'Annullato')], default='CONFERMATO', max_length=20)),
                ('data_annullamento', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordini', to='winery.agente')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordini', to='winery.cliente')),
            ],
            options={
                'verbose_name_plural': 'Ordini',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='RigaOrdineBottiglia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_etichetta', models.BooleanField(default=True)),
                ('ha_capsula', models.BooleanField(default=True)),
                ('quantita', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe_bottiglie', to='winery.ordine')),
                ('tipologia_vino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='winery.tipologiavino')),
            ],
            options={
                'verbose_name_plural': 'Righe ordine bottiglie',
            },
        ),
        migrations.CreateModel(
            name='RigaOrdineGadget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe_gadget', to='winery.ordine')),
                ('tipo_gadget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='winery.tipogadget')),
            ],
            options={
                'verbose_name_plural': 'Righe ordine gadget',
            },
        ),
    ]
